version: '3.1'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://localhost:5432/invoice
      - DB_USER=postgres
      - DB_PASSWORD=password
      - S3_REGION=eu-west-3
      - S3_BUCKET_NAME=mabdi-invoices
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=invoice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
