server:
    port: 8080
  
aws:
    s3:
        region: ${S3_REGION}
        bucketName: ${S3_BUCKET_NAME}

spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver